SG-34298 - Rebranding
shotgunsoftware/tk-framework-alias pull request #37
Opened 2024-01-25 13:21 UTC by juanburgosautoglb

Change all the shotgrid/shotgun occurrences in the repository.

2024-01-30 17:02 UTC, staceyoue reviewed
@juanburgosautoglb why was the icon changed from the Alias icon to the Canadian flag?

2024-02-28 19:41 UTC, julien-lang requested changes

2024-02-28 19:41 UTC, julien-lang commented on README.md
> +The main use of this framework is by the [Alias Engine](https://github.com/shotgunsoftware/tk-alias). The framework allows the engine to run alongside Alias, providing access to the Flow Production T
```suggestion
The main use of this framework is by the [Alias Engine](https://github.com/shotgunsoftware/tk-alias). The framework allows the engine to run alongside Alias, providing access to the Flow Production Tracking Toolkit Apps that can interact with the data in Alias.
```

2024-02-28 19:41 UTC, julien-lang commented on dev/README.md
> +The framework requires additional Python packages to the standard package that Flow Production Tracking ships with. To make these packages available to the framework, they must be included in the dis
```suggestion
The framework requires additional Python packages to the standard package that Flow Production Tracking Toolkit ships with. To make these packages available to the framework, they must be included in the distribution directory `dist/Python/Python<MAJOR_VERSION><MINOR_VERSION>/packages`.
```

2024-02-28 19:41 UTC, julien-lang commented on dist/README.md
> +Additional Python packages are required to run the framework that Flow Production Tracking does not ship with. These packages are added to the Python system path at run time [here](https://github.com
```suggestion
Additional Python packages are required to run the framework that Flow Production Tracking Toolkit does not ship with. These packages are added to the Python system path at run time [here](https://github.com/shotgunsoftware/tk-framework-alias/blob/develop/python/tk_framework_alias/__init__.py#L11-L20). By including the packages in the path, these modules must be made available by either:
```

2024-02-28 19:42 UTC, julien-lang approved these changes

2024-03-20 19:47 UTC, merged